---
title: "Final"
author: "Shengzhi Luo"
date: "06/05/2022"
output: pdf_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(viridis)
library(mlbench)
library(ISLR)
library(caret)
library(e1071)
library(kernlab)
library(factoextra)
library(gridExtra)
library(corrplot)
library(RColorBrewer) 
library(gplots)
library(jpeg)
library(MASS)
library(pROC)
library(klaR)
library(pdp)
library(vip)
library(AppliedPredictiveModeling)
library(mgcv)
library(nlme)
library(rpart)
library(rpart.plot)
library(party)
library(partykit)
library(randomForest)
library(ranger)
library(gbm)
library(ggplot2)
library(ggpubr)
```

# Data load and pre-process

```{r message=FALSE}
# Load data, clean column names, eliminate indexs containing NA entries
heartattack = read_csv("heartattack.csv") %>%
              mutate(
                sex = factor(sex,ordered=TRUE),
                exng = factor(exng,ordered = TRUE),
                cp = factor(cp,ordered = TRUE),
                fbs = factor(fbs,ordered = TRUE),
                restecg = factor(restecg,ordered = TRUE),
                output = factor(case_when(output== 0 ~ "less",
                                   output == 1 ~ "more")),
                output = fct_relevel(output, "less")
              )%>%
  na.omit()%>%
  dplyr::select(-thall, -slp)

knitr::opts_chunk$set(warning = FALSE, message = FALSE, fig.align = "center")
theme_set(theme_minimal() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d


```

```{r}
set.seed(100)
# Partition data into training/test sets
indexTrain = createDataPartition(y = heartattack$output,
                                 p = 0.7,
                                 list = FALSE)
training_df = heartattack[indexTrain, ]
testing_df = heartattack[-indexTrain, ]
# Create matrices for future analysis
# Training data
x_train = model.matrix(output~.,training_df)[, -11]
y_train = training_df$output
# Testing data
x_test <- model.matrix(output~.,testing_df)[, -11]
y_test <- testing_df$output
x_train_df = data.frame(x_train)
```

```{r}
summary(heartattack)
skimr::skim_without_charts(heartattack)
```

```{r}
theme1 = transparentTheme(trans = 0.4)
trellis.par.set(theme1)
featurePlot(x = heartattack %>% dplyr::select(age, caa, trtbps, thalachh,chol,oldpeak),
            y = heartattack$output,
            scales = list(x = list(relation = "free"),
                          y = list(relation = "free")),
            plot = "density", pch = "|",
            auto.key = list(columns = 2))
```

```{r}
par(mfrow = c(2, 3))
fp1 <- ggplot(training_df) + geom_bar(aes(x = sex)) 
fp2 <- ggplot(training_df) + geom_bar(aes(x = cp)) 
fp3 <- ggplot(training_df) + geom_bar(aes(x = fbs)) 
fp4 <- ggplot(training_df) + geom_bar(aes(x = restecg)) 
fp5 <- ggplot(training_df) + geom_bar(aes(x = exng))
figure <- ggarrange(fp1,fp2, fp3, fp4, fp5,
                    ncol = 2, nrow = 3)
figure
```



## glm
```{r}
set.seed(100)
ctrl = trainControl(method = "cv",
                    summaryFunction = twoClassSummary,
                    classProbs = TRUE)

model.glm <- train(output ~ . , heartattack,
                   subset = indexTrain,
                    method = "glm",
                    metric = "ROC",
                    trControl = ctrl)

```

## penalized glm
```{r}
glmnGrid <- expand.grid(.alpha = seq(0, 1, length = 11),
                        .lambda = exp(seq(2, -2, length = 35)))
set.seed(100)
model.glmn <- train(output ~ . , heartattack,
                   subset = indexTrain,
                    method = "glmnet",
                    tuneGrid = glmnGrid,
                    metric = "ROC",
                    trControl = ctrl)

model.glmn$bestTune

myCol<- rainbow(15)
myPar <- list(superpose.symbol = list(col = myCol),
              superpose.line = list(col = myCol))

plot(model.glmn, par.settings = myPar, xTrans = function(x) log(x))

```

## Mars
```{r, warning=FALSE}
set.seed(100)
model.mars <- train(output ~ . , heartattack,
                   subset = indexTrain,
                    method = "earth",
                    tuneGrid = expand.grid(degree = 1:3, 
                                           nprune = 2:15),
                    metric = "ROC",
                    trControl = ctrl)

plot(model.mars)

coef(model.mars$finalModel) %>% knitr::kable(col.names = "Coefficient") 
```


## LDA

```{r}
partimat(output~age+caa+trtbps+chol+thalachh, method = "lda", data = heartattack)

lda.fit <- lda(output~., data = heartattack,subset = indexTrain)

plot(lda.fit, col = as.numeric(heartattack$output), abbrev = TRUE)

lda.fit$scaling


set.seed(100)
model.lda = train(output ~ . , heartattack,
                   subset = indexTrain,
                  method = "lda",
                  metric = "ROC",
                  trControl = ctrl)

```

# CTREE

```{r}
set.seed(100)

tree1 <- rpart(formula = output ~ . ,data = heartattack, subset = indexTrain, control = rpart.control(cp = 0))

rpart.plot(tree1)

printcp(tree1)

cpTable <- tree1$cptable
plotcp(tree1)

minErr <- which.min(cpTable[,4])
tree2 <- prune(tree1, cp = cpTable[minErr,1])
rpart.plot(tree2)

set.seed(100)
model.ctree <- train(output ~ . , heartattack,
                   subset = indexTrain,
                   method = "ctree",
                   tuneGrid = data.frame(mincriterion = 1-exp(seq(-2, -1, length = 50))),
                   metric = "ROC",
                   trControl = ctrl)
```

# Random Tree

```{r}
set.seed(100)

model.rpart <- train(output ~ . ,
                   heartattack,
                   subset = indexTrain,
                   method = "rpart",
                   tuneGrid = data.frame(cp = exp(seq(-6,-3, len = 50))),
                   trControl = ctrl,
                   metric = "ROC")
```


# 
```{r}

rf.grid <- expand.grid(mtry = 1:8,
                       splitrule = "gini",
                       min.node.size = seq(from = 2, to = 10, by = 2))
set.seed(1)
model.rf<- train(output ~ . ,
                   heartattack,
                   subset = indexTrain,
                method = "ranger",
                tuneGrid = rf.grid,
                metric = "ROC",
                trControl = ctrl)
ggplot(model.rf, highlight = TRUE)
```

# AdaBoost

```{r}
gbmA.grid <- expand.grid(n.trees = c(2000,3000,4000,5000),
                         interaction.depth = 1:6,
                         shrinkage = c(0.0005,0.001,0.002),
                         n.minobsinnode = 1)
set.seed(1)
model.gbmA <- train(output ~ . ,
                   heartattack,
                   subset = indexTrain,
                  tuneGrid = gbmA.grid,
                  trControl = ctrl,
                  method = "gbm",
                  distribution = "adaboost",
                  metric = "ROC",
                  verbose = FALSE)

ggplot(model.gbmA, highlight = TRUE)

#gbmA.pred <- predict(gbmA.fit, newdata = dat[-rowTrain,], type = "prob")[,1]
```
# GAM
```{r}
set.seed(100)
model.gam<- train(output ~ . ,
                   heartattack,
                   subset = indexTrain,
                 method="gam",
                 metric = "ROC",
                 tuneGrid = data.frame(method = "GCV.Cp",select=c(TRUE,FALSE)),
                 trControl = ctrl)
model.gam$bestTune
model.gam$results
model.gam$finalModel
```


# NB
```{r,warning=FALSE}
nbGrid <- expand.grid(usekernel = c(FALSE,TRUE),
                      fL = 1,
                      adjust = seq(.1, 1, by = .1))
set.seed(100)
model.nb <- train(output ~ . ,
                   heartattack,
                   subset = indexTrain,
                  method = "nb",
                  tuneGrid = nbGrid,
                  metric = "ROC",
                  trControl = ctrl)
plot(model.nb)
```


```{r,warning=FALSE,message=FALSE}
res <- resamples(list(GLM = model.glm, GLMNET = model.glmn, MARS = model.mars, CTREE = model.ctree, RPART = model.rpart, LDA = model.lda, RF = model.rf, GBMA = model.gbmA,NB = model.nb,GAM = model.gam))
trainROC <- bwplot(res, metric = "ROC")
summary(res)
trainROC
```


```{r,warning=FALSE,message=FALSE}
lda.pred <- predict(model.lda, newdata = heartattack[-indexTrain,], type = "prob")[,2]
rpart.pred <- predict(model.rpart, newdata = heartattack[-indexTrain,],type = "prob")[,2]
ctree.pred <- predict(model.ctree, newdata = heartattack[-indexTrain,],type = "prob")[,2]
glm.pred <- predict(model.glm, newdata = heartattack[-indexTrain,], type = "prob")[,2]
glmn.pred <- predict(model.glmn, newdata = heartattack[-indexTrain,], type = "prob")[,2]
mars.pred <- predict(model.mars, newdata = heartattack[-indexTrain,], type = "prob")[,2]
rf.pred <- predict(model.rf, newdata = heartattack[-indexTrain,], type = "prob")[,2]
gbmA.pred <- predict(model.gbmA, newdata = heartattack[-indexTrain,], type = "prob")[,2]
nb.pred <- predict(model.nb, newdata = heartattack[-indexTrain,], type = "prob")[,2]
gam.pred <- predict(model.gam, newdata = heartattack[-indexTrain,], type = "prob")[,2]
  
roc.lda <- roc(heartattack$output[-indexTrain], lda.pred)
roc.rpart <- roc(heartattack$output[-indexTrain], rpart.pred)
roc.ctree <- roc(heartattack$output[-indexTrain], ctree.pred)
roc.glm <- roc(heartattack$output[-indexTrain], glm.pred)
roc.glmn <- roc(heartattack$output[-indexTrain], glmn.pred)
roc.mars <- roc(heartattack$output[-indexTrain], mars.pred)
roc.rf <- roc(heartattack$output[-indexTrain], rf.pred)
roc.gbmA <- roc(heartattack$output[-indexTrain], gbmA.pred)
roc.nb <- roc(heartattack$output[-indexTrain], nb.pred)
roc.gam <- roc(heartattack$output[-indexTrain], gam.pred)

auc <- c(roc.lda$auc[1],roc.rpart$auc[1], roc.ctree$auc[1], roc.glm$auc[1], roc.glmn$auc[1], roc.rf$auc[1],roc.mars$auc[1],roc.gbmA$auc[1],roc.nb$auc[1],roc.gam$auc[1])


plot(roc.lda, legacy.axes = TRUE)
plot(roc.rpart, legacy.axes = TRUE)
plot(roc.ctree, col = 2, add = TRUE)
plot(roc.glm, col = 2, add = TRUE)
plot(roc.glmn, col = 2, add = TRUE)
plot(roc.mars, col = 2, add = TRUE)
plot(roc.rf, col = 2, add = TRUE)
plot(roc.gbmA, col = 2, add = TRUE)
plot(roc.nb, col = 2, add = TRUE)
plot(roc.gam, col = 2, add = TRUE)

modelNames <- c("lda", "rpart", "ctree", "glm", "glmn", "mars","rf","gbmA","nb","gam")

ggroc(list(roc.lda, roc.rpart ,roc.ctree, roc.glm, roc.glmn, roc.mars,roc.rf,roc.gbmA,roc.nb,roc.gam), legacy.axes = TRUE) +
scale_color_discrete(labels = paste0(modelNames, " (", round(auc,3),")"),
name = "Models (AUC)") +
geom_abline(intercept = 0, slope = 1, color = "grey")
```




## Variable Importance
```{r vip,cache=TRUE}
glm.vip <- varImp(model.glm)$importance
glmn.vip <- varImp(model.glmn)$importance
mars.vip <- varImp(model.mars)
rpart.vip <- varImp(model.rpart)$importance
vip1 <- vip(model.mars$finalModel)
vip2 <- vip(model.glmn$finalModel)
vip <- grid.arrange(vip1,vip2)
```


## PDP
```{r,warning=FALSE}
pdp.rf <- model.rf %>% 
  partial(pred.var = "thalachh", 
          grid.resolution = 100,
          prob = TRUE) %>%
  autoplot(rug = TRUE, train = training_df) +
  ggtitle("Random forest") 

pdp.gbmA <- model.gbmA %>% 
  partial(pred.var = "thalachh", 
          grid.resolution = 100,
          prob = TRUE) %>%
  autoplot(rug = TRUE, train = training_df) +
  ggtitle("Boosting") 

grid.arrange(pdp.rf, pdp.gbmA,nrow = 1)
```


# Individual conditional expectation (ICE) curves
```{r, fig.width = 8, fig.height = 4,warning=FALSE}
ice1.rf <- model.rf %>% 
  partial(pred.var = "thalachh", 
          grid.resolution = 100,
          ice = TRUE) %>%
  autoplot(train = training_df, alpha = .1) +
  ggtitle("ICE, not centered") 

ice2.rf <- model.rf %>% 
  partial(pred.var = "thalachh", 
          grid.resolution = 100,
          ice = TRUE) %>%
  autoplot(train = training_df, alpha = .1, 
           center = TRUE) +
  ggtitle("ICE, centered") 


grid.arrange(ice1.rf, ice2.rf, nrow = 1)
```

# Support Vector
```{r}
set.seed(5009)
linear.tune <- tune.svm(output ~ . , 
                        data = training_df, 
                        kernel = "linear", 
                        cost = exp(seq(-5,2,len=50)),
                        scale = TRUE)
plot(linear.tune)
#summary(linear.tune)

linear.tune$best.parameters

best.linear <- linear.tune$best.model
summary(best.linear)
pred.linear <- predict(best.linear, newdata = testing_df)

confushion_test <- confusionMatrix(data = pred.linear, 
                reference = heartattack$output[-indexTrain])
confushion_test
```
```{r}
set.seed(5009)
radial.tune <- tune.svm(output ~ . , 
                        data = training_df, 
                        kernel = "radial", 
                        cost = exp(seq(-1,4,len=20)),
                        gamma = exp(seq(-6,-2,len=20)))

plot(radial.tune, transform.y = log, transform.x = log, 
     color.palette = terrain.colors)
# summary(radial.tune)
radial.tune$best.parameters
best.radial <- radial.tune$best.model
summary(best.radial)
pred.radial <- predict(best.radial, newdata = heartattack[-indexTrain,])

confusionMatrix(data = pred.radial, 
                reference = heartattack$output[-indexTrain])
```


```{r}
heartattack_dat = heartattack %>% as.data.frame()
hc.complete <- hclust(dist(heartattack_dat), method = "complete")
fviz_dend(hc.complete, k = 3,        
          cex = 0.3, 
          palette = "jco", 
          color_labels_by_k = TRUE,
          rect = TRUE, rect_fill = TRUE, rect_border = "jco",
          labels_track_height = 2.5)
```




